PACKAGE_PATH = $(shell pwd)

SRC = ./firmware/hdl/top/VertexFinderProcessor.vhd
TESTBENCH = ./firmware/hdl/testbench/TestBench.vhd

INCLUDE_PATHS = \
	firmware/hdl \
	../RuflCore/firmware/hdl

include $(PACKAGE_PATH)/../RuflCore/config/mfRules.mk
